### ISSUE TITLE
Where did δ and π implemented in code? 

### ISSUE THREAD

**Issue by zbwxp** [Megvii-BaseDetection/BorderDet#10]
Hi, thank you for your fantastic work. Could you please point out the location of the δ and π that in your paper mentioned?

"The π indicates multiplication and the δ denotes the combination of the two bounding box locations "

thank you very much

**Comment by Maycbj** [comment]
Hi, thank you for your attention！
classification(δ): https://github.com/Megvii-BaseDetection/BorderDet/blob/master/cvpods/modeling/meta_arch/borderdet.py#L526 
regression(π): https://github.com/Megvii-BaseDetection/BorderDet/blob/master/cvpods/modeling/meta_arch/borderdet.py#L546

**Comment by zbwxp** [comment]
Thank you for your reply. Am I understand this correct:

The π and δ process were never involved during training process. The four losses: original FCOS cls, original FCOS reg. border cls, border reg δ are 4 parallel branches when training. Only when validation, the result of FCOS cls and border cls are multiplied togeter ( π)  and FCOS reg and border reg δ are added up together?

Have you tried to group them together from 4 branches to two branches(1.FCOS cls * border cls, 2. FCOS reg + border reg δ) and directly train their corresponding loss (ground truth cls and reg)  during training as a more 'end-to-end' form?  Will that work?

Thank you very much.

**Comment by Maycbj** [comment]
Yeah, we have done these experiments before, but it does not work.
A reasonable explanation is that the bounding box distributions are different in different stage, so the label assignment of them are not exactly the same. 
Besides, similar to the Cascade R-CNN, we train the different stage with separate losses, and it is indeed better than the joint modeling.
