### ISSUE TITLE
How to visualize results?

### ISSUE THREAD

**Issue by bjxchang** [Megvii-BaseDetection/BorderDet#12]
Hi,
Could you please support a tool to visualize the inference results?
Thanks a lot!

**Comment by Maycbj** [comment]
We have already support visualization of the detection results. Do you have the plan to release the code of visualization recently？ @FateScript

**Comment by FateScript** [comment]
> We have already support visualization of the detection results. Do you have the plan to release the code of visualization recently？ @FateScript

@bjxchang we will release a new version cvpods in a month. If you want visualize data in a hurry, please check demo mode.

**Comment by bjxchang** [comment]
@FateScript Thanks. I will check the demo mode first.
