### ISSUE TITLE
不太理解BAM模块与Coarse Box Reg之间具体是怎么作用的，代码里面也没看懂，烦请解答一下

### ISSUE THREAD

**Issue by BITQinYong** [Megvii-BaseDetection/BorderDet#13]
如问题

**Comment by Maycbj** [comment]
首先，BAM模块的输入有两个: feature(N,C,H,W), coarse box(N,4,H,W)。
step1. 会先把feature用1x1conv去提升通道数到(N,5C,H,W)，为了location sensitive，不同通道对应不同位置。
step2. coarse box代表每个点都会生成一个box，用这个box的坐标，就可以得到每条边上对应的n个采样点的位置，由于采样点是浮点数，所以需要用双线性插值插出来。每条边会插值出来的n个点，做max-pooling，就只剩下一个点，大小是(4C, 1, 1)，加上原始anchor点的特征，就是(5C, 1, 1)，把这个特征放到anchor点的位置，就完成一个点的操作。
step3. (N,4,H,W)上每个框都进行step2，则输出的结果就是(N,5C,H,W).
总的来说，BorderAlign中每个coarse box对应的采样点的个数比RoIALign少很多，所以速度上也是有优势的。
不知道你大概明白了没。
<img src="https://user-images.githubusercontent.com/19340566/92855498-eec35480-f424-11ea-86c4-26d26bfec04a.png" height="200px" width="520px" >

**Comment by BITQinYong** [comment]
大概明白了，真的非常感谢
