### ISSUE TITLE
ImportError: cannot import name 'config'

### ISSUE THREAD

**Issue by fumingheng** [Megvii-BaseDetection/BorderDet#16]
When I run train_net.py ,it shows this error .Can you tell why ,thanks!
/content/drive/My Drive/BorderDet/BorderDet/tools
pods_test  pods_train  test_net.py  train_net.py
Traceback (most recent call last):
  File "train_net.py", line 38, in <module>
    from config import config
ImportError: cannot import name 'config'

**Comment by FateScript** [comment]
Please run cvpod_train under dir like [this](https://github.com/Megvii-BaseDetection/BorderDet/tree/master/playground/detection/coco/borderdet/borderdet.res50.fpn.coco.800size.1x). otherwise cvpods will not find your config and network.

Read the README.md carefully, please.

**Comment by shenhaibb** [comment]
i run cvpods_train under dir like what you said
however, cvpods cant find config and network, why?
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/64736467/164607855-7e61068f-683b-4bbf-814f-17c638be381d.png">
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/64736467/164607958-97cf1f4f-4721-4366-a4d8-37120922b093.png">
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/64736467/164607983-175e198f-d570-4d26-aa74-fcce65b98543.png">
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/64736467/164608303-c27eca41-11e4-4e84-ae60-8cff28f0cb46.png">
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/64736467/164608368-359962ab-b267-4a09-b05c-c809cf338965.png">
Did I get the directory structure wrong？

**Comment by shenhaibb** [comment]
I manually raised the cvpods file in cvpods folder.
And is this the 'DefaultCheckpoint'?
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/64736467/164617389-94b6e050-f9cb-4ced-8378-dad3f483c3e0.png">

**Comment by shenhaibb** [comment]
I manually raised the cvpods file in cvpods folder, then 
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/64736467/164617918-7186739f-5e38-4a6f-90c0-07dfbbcb8d80.png">
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/64736467/164620395-ece4a846-54fb-4a7c-a44c-d6481b2d4968.png">
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/64736467/164620622-c378acec-f99c-4177-b1e4-25cdb5f56c75.png">
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/64736467/164620836-7bacb4c6-a71a-4d02-bdfa-c5a24aa26449.png">

**Comment by FateScript** [comment]
@shenhaibb  Please provide text error log next time, thanks. Image is not convenient for users to search and for me to check.

For your issue, it seems that your cvpods doesn't contains checkpoint  in utils directory.

**Comment by shenhaibb** [comment]
> 
sorry, i will provide text instead of image next time

我的目录结构如下：
- BordeDet-master
    - playgound
    - tools
    - ...
    - cvpods
        - cvpods
            - checkpoints
            - configs
        - datasets
        - tools
        - ...

**Comment by shenhaibb** [comment]
Shoud i put all codes in BorderDet-master into cvpods-master folder?
I hava tried many structure but no one work

**Comment by FateScript** [comment]
Oh, I see. `from cvpods.checkpoint import DetectionCheckpointer`
Change this into `from cvpods.checkpoint import DefaultCheckpointer as DetectionCheckpointer`

Reference:
code [here](https://github.com/Megvii-BaseDetection/cvpods/blob/master/cvpods/checkpoint/checkpoint.py#L413-L414)

**Comment by shenhaibb** [comment]
> > 
> 
> sorry, i will provide text instead of image next time
> 
> 我的目录结构如下：
> 
> * BordeDet-master
>   
>   * playgound
>   * tools
>   * ...
>   * cvpods
>     
>     * cvpods
>       
>       * checkpoints
>       * configs
>     * datasets
>     * tools
>     * ...

There seems to be a problem with this directory structure.
After compiling, `from cvpods layers, modeling, structure...` in borderdet.py cant be imported
I think the cvpods folder should contain the borderdet folder (trying)
- cvpods
    - cvpods
        - checkpoints
        - configs
        - ...
    - datasets
    - BordeDet
        - playground
        - tools

And setup.py in the BorderDet
`def get_version():`
     `init_py_path = path.join(path.abspath(path.dirname(__file__)), "cvpods", "__init__.py")`

Do we need to replace it with the following code:

 `init_py_path = path.join(path.abspath(path.dirname(__file__)), "cvpods", "cvpods", "__init__.py")`

Otherwise it will show the fault

`No such file or directory: 'BorderDet/cvpods/__init__.py'`

Or what is the correct directory structure of the item?

**Comment by FateScript** [comment]
Why you have two cvpods?

**Comment by FateScript** [comment]
Did you cd your path to cvpods and run setup.py ? Plz don't use setup.py in BorderDet

**Comment by shenhaibb** [comment]
> Did you cd your path to cvpods and run setup.py ? Plz don't use setup.py in BorderDet

`git clone https://github.com/Megvii-BaseDetection/cvpods.git`

the name of this repo is cvpods, and there is a folder named cvpods in this repo

**Comment by shenhaibb** [comment]
> Did you cd your path to cvpods and run setup.py ? Plz don't use setup.py in BorderDet

I use Pycharm, download BorderDet and put it into Pycharm
then I git clone cvpods.git in BorderDet's path

**Comment by shenhaibb** [comment]
my directory structure like this,
- cvpods-master
    - cvpods
        - checkpoints
        - configs
        - ...
    - datasets
    - BordeDet
        - playground
        - tools

and then I enter this cmd `cd BorderDet/playground/detection/coco/borderdet/borderdet.res50.fpn.coco.800size.1x`
`pods_train --num-gpus 8`

No module named 'config' in 'cvpods-master/tools/train_net.py', line 151

**Comment by shenhaibb** [comment]
hey I solved it
my directory structure like this,
- cvpods-master
    - cvpods
        - checkpoints
        - configs
        - ...
    - datasets
    - BordeDet
        - playground
        - tools

then `cd BorderDet && python3 setup.py build develop`
there will be an error `No such file or directory: 'BorderDet/cvpods/__init__.py'` never mind
under BorderDet/tools, new 2 files 'pods_test' and `pods_train` can be seen

and then delete Line 192 in cvpods-master/setup.py, because there is no tools/pods_debug, and add BorderDet path like below
`scripts=[
            "BorderDet/tools/pods_train",
            "BorderDet/tools/pods_test"
        ],`

and then enter cmd `python3 setup.py build develop` under cvpods-master
`FInished processing dependencies for cvpods==0.1...`

then turn to BorderDet/tools/train_net.py
there is an error in Line 26, change to below code.
`from cvpods.checkpoint.checkpoint import DetectionCheckpointer`

then `cd BorderDet/playground/detection/coco/borderdet/borderdet.res50.fpn.coco.800size.1x`
and `pods_train --num-gpus 8`

**Comment by shenhaibb** [comment]
`Permission denied: '/data'`

turn to `BorderDet/playground/detection/coco/borderdet/borderdet.res50.fpn.coco.800size.1x/config.py`
Line 63 `'/data/Outputs/model_logs/cvpods_playground',`
change to `'data/Outputs/model_logs/cvpods_playground',`

**Comment by shenhaibb** [comment]
Traceback (most recent call last):
  File "/media/henu/新加卷1/rxh/cvpods-master/BorderDet/tools/train_net.py",
 line 216, in <module>
    launch(
  File "/media/henu/新加卷1/rxh/cvpods-master/cvpods/engine/launch.py", lin
e 64, in launch
    main_func(*args)
  File "/media/henu/新加卷1/rxh/cvpods-master/BorderDet/tools/train_net.py",
 line 203, in main
    stage_main(args, config, build_model)
  File "/media/henu/新加卷1/rxh/cvpods-master/BorderDet/tools/train_net.py",
 line 126, in stage_main
    cfg, logger = default_setup(cfg, args)


Is it produced by my change ？
