### ISSUE TITLE
ImportError: Undefine Symbol

### ISSUE THREAD

**Issue by SilenceX12138** [Megvii-BaseDetection/BorderDet#17]
I follow the commands in README but when I get to train the net, following error comes out:
>  ./cvpods/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol:  _ZN6cvpods25ComputeAdaptiveLrOnDeviceEN2at6TensorES1_dddS1_

All environment is set as the requirements.txt said, and the GPU is alright for I could run other DL projects.

Please help to take a look at it, thanks~

**Comment by FateScript** [comment]
This **[issue](https://github.com/Megvii-BaseDetection/BorderDet/issues/6)** might help you.
