### ISSUE TITLE
BorderDet in FCOS

### ISSUE THREAD

**Issue by Tangzhaotz** [Megvii-BaseDetection/BorderDet#20]
您好，我想问以下，因为当前一些目标跟踪算法采用FCOS，所以我想在当前算法加入BAM模块，请问一下具体的代码参考哪些？谢谢

**Comment by FateScript** [comment]
borderdet代码在[这里](https://github.com/Megvii-BaseDetection/BorderDet/blob/master/cvpods/modeling/meta_arch/borderdet.py)
module部分在[这里](https://github.com/Megvii-BaseDetection/BorderDet/blob/master/cvpods/layers/border_align.py)

**Comment by Tangzhaotz** [comment]
> borderdet代码在[这里](https://github.com/Megvii-BaseDetection/BorderDet/blob/master/cvpods/modeling/meta_arch/borderdet.py)
> module部分在[这里](https://github.com/Megvii-BaseDetection/BorderDet/blob/master/cvpods/layers/border_align.py)
谢谢

**Comment by Tangzhaotz** [comment]
> borderdet代码在[这里](https://github.com/Megvii-BaseDetection/BorderDet/blob/master/cvpods/modeling/meta_arch/borderdet.py)
> module部分在[这里](https://github.com/Megvii-BaseDetection/BorderDet/blob/master/cvpods/layers/border_align.py)
https://github.com/Megvii-BaseDetection/BorderDet/blob/master/cvpods/layers/csrc/border_align/border_align_kernel.c
再请教一下，这个代码是用什么写的，看不太懂

**Comment by FateScript** [comment]
> > borderdet代码在[这里](https://github.com/Megvii-BaseDetection/BorderDet/blob/master/cvpods/modeling/meta_arch/borderdet.py)
> > module部分在[这里](https://github.com/Megvii-BaseDetection/BorderDet/blob/master/cvpods/layers/border_align.py)
> > https://github.com/Megvii-BaseDetection/BorderDet/blob/master/cvpods/layers/csrc/border_align/border_align_kernel.cu
> > 再请教一下，这个代码是用什么写的，看不太懂

这段是cuda代码
