### ISSUE TITLE
Can someone implement this repo by only pytorch and python?

### ISSUE THREAD

**Issue by shaojiestar** [Megvii-BaseDetection/BorderDet#21]
I'm a noob of DL.
the code in this repo is very difficult for me.
but I very want to use this tech.
Please help me.
thank you very much.

**Comment by FateScript** [comment]
Hi, this repo is written in Pytorch and Python3, so I'm confused about your issue, could you explain it?

**Comment by FateScript** [comment]
Since the reporter doesn't reply for more than a week, We close this issue.

**Comment by xiaowenhe** [comment]
> Hi, this repo is written in Pytorch and Python3, so I'm confused about your issue, could you explain it?

意思应该是  BorderAlign是否也可以给torch或者python版本的，你们目前不是C实现的吗?!
