### ISSUE TITLE
Darknet pretrained model

### ISSUE THREAD

**Issue by Trouble404** [Megvii-BaseDetection/BorderDet#23]
Hi, thanks for your work, I am also interested in other detectors in cvpods, I want to know where to find "s3://generalDetection/cvpods/ImageNetPretrained/custom/darknet53.mix.pth" this darknet pretrained model.

**Comment by FateScript** [comment]
Hi, boraderdet is part of cvpods, we just release some parts of it, not all models.

We might release them all in the future.
