### ISSUE TITLE
边界点的正负样本定义

### ISSUE THREAD

**Issue by Tangzhaotz** [Megvii-BaseDetection/BorderDet#25]
您好，我想请问一下边界上的正负样本定义是根据预测得到的粗略的边框与真实边框的IOU来确定的吗？这部分代码不是很懂，希望能解答一下，谢谢

**Comment by FateScript** [comment]
PTAL @Maycbj

**Comment by Maycbj** [comment]
是的，是用的预测得到的粗略的边框(第一阶段的框)与真实边框的IOU来确定的。
https://github.com/Megvii-BaseDetection/BorderDet/blob/master/cvpods/modeling/meta_arch/borderdet.py#L442
