### ISSUE TITLE
I have a question about this code.

### ISSUE THREAD

**Issue by 2gunsu** [Megvii-BaseDetection/BorderDet#26]
Thank you for sharing this great project.
I am new to deep learning and have a question about code.

On line 67 of cvpods> modeling> meta_arch> ssd.py,
```python
self.default_box_generator = cfg.build_default_box_generator(cfg)
```
Where can i find `build_default_box_generator`?

**Comment by FateScript** [comment]
Sorry, This part of code is not released yet since borderdet has nothing to do with SSD.

**Comment by 2gunsu** [comment]
Thanks! :)
