### ISSUE TITLE
How to train for custom dataset

### ISSUE THREAD

**Issue by PhanVinhLong** [Megvii-BaseDetection/BorderDet#27]
Thanks for your great work.
I want to train BorderDet with my custom dataset (difference classes) from scratch/ transfer learning. How can I do that?
Thank you.

**Comment by Maycbj** [comment]
You can refer to the [code](https://github.com/Megvii-BaseDetection/BorderDet/tree/master/cvpods/data/datasets) under this folder to construct your dataset，and modify the setting of the config [code](https://github.com/Megvii-BaseDetection/BorderDet/blob/master/playground/detection/coco/fcos/fcos.res50.fpn.coco.800size.1x/config.py#L29).
Then you can train your custom dataset!
