### ISSUE TITLE
from cvpods import _C

### ISSUE THREAD

**Issue by Tangzhaotz** [Megvii-BaseDetection/BorderDet#29]
from cvpods import _C
ImportError: cannot import name '_C' from 'cvpods' (BorderDet/cvpods/__init__.py)

您好，我没找到_C在哪？文件里面貌似没有

**Comment by FateScript** [comment]
这个是你build出来的

**Comment by Tangzhaotz** [comment]
> 这个是你build出来的

请问可以解释具体一点吗？不太懂

**Comment by lxtGH** [comment]
需要cude编译安装

**Comment by Tangzhaotz** [comment]
> 需要cude编译安装

setup.py那个吗？

**Comment by Tangzhaotz** [comment]
> 需要cude编译安装

好了，谢谢
