### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by hanbingmew** [Megvii-BaseDetection/BorderDet#30]
python setup.py build develop
running build
running build_py
running build_ext
building 'cvpods._C' extension
Emitting ninja build file /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.7.2
g++ -pthread -shared -L/home/ldd/anaconda3/envs/pytorch1.5/lib -Wl,-rpath=/home/ldd/anaconda3/envs/pytorch1.5/lib,--no-as-needed /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/vision.o /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/nms_rotated/nms_rotated_cpu.o /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/box_iou_rotated/box_iou_rotated_cpu.o /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/ROIAlign/ROIAlign_cpu.o /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/ROIAlignRotated/ROIAlignRotated_cpu.o /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/sigmoid_focal_loss/SigmoidFocalLoss_cuda.o /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/deformable/deform_conv_cuda.o /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/deformable/deform_conv_cuda_kernel.o /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/nms_rotated/nms_rotated_cuda.o /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/SwapAlign2Nat/SwapAlign2Nat_cuda.o /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/box_iou_rotated/box_iou_rotated_cuda.o /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/ROIAlign/ROIAlign_cuda.o /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/lars/adaptive_lr_cuda.o /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/border_align/border_align_kernel.o /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/ROIAlignRotated/ROIAlignRotated_cuda.o /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/ml_nms/ml_nms.o /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/cuda_version.o -L/home/ldd/anaconda3/envs/pytorch1.5/lib/python3.6/site-packages/torch/lib -L/usr/local/cuda/lib64 -L/home/ldd/anaconda3/envs/pytorch1.5/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -lpython3.6m -o build/lib.linux-x86_64-3.6/cvpods/_C.cpython-36m-x86_64-linux-gnu.so
g++: error: /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/lars/adaptive_lr_cuda.o: No such file or directory
error: command 'g++' failed with exit status 1

Could anyone help me with this problem

**Comment by FateScript** [comment]
That means that you doesn't have compile environment. Please install g++ for compile first, Thanks.

**Comment by hanbingmew** [comment]
I have already installed g++ and it can compile other projects. It seems that my g++ can't generate .o files in this project.
g++: error: /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/vision.o: No such file or directory
g++: error: /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/nms_rotated/nms_rotated_cpu.o: No such file or directory
g++: error: /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/box_iou_rotated/box_iou_rotated_cpu.o: No such file or directory
g++: error: /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/ROIAlign/ROIAlign_cpu.o: No such file or directory
g++: error: /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/ROIAlignRotated/ROIAlignRotated_cpu.o: No such file or directory
g++: error: /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/sigmoid_focal_loss/SigmoidFocalLoss_cuda.o: No such file or directory
g++: error: /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/deformable/deform_conv_cuda.o: No such file or directory
g++: error: /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/deformable/deform_conv_cuda_kernel.o: No such file or directory
g++: error: /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/nms_rotated/nms_rotated_cuda.o: No such file or directory
g++: error: /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/SwapAlign2Nat/SwapAlign2Nat_cuda.o: No such file or directory
g++: error: /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/box_iou_rotated/box_iou_rotated_cuda.o: No such file or directory
g++: error: /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/ROIAlign/ROIAlign_cuda.o: No such file or directory
g++: error: /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/lars/adaptive_lr_cuda.o: No such file or directory
g++: error: /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/border_align/border_align_kernel.o: No such file or directory
g++: error: /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/ROIAlignRotated/ROIAlignRotated_cuda.o: No such file or directory
g++: error: /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/ml_nms/ml_nms.o: No such file or directory
g++: error: /home/ldd/BorderDet/build/temp.linux-x86_64-3.6/home/ldd/BorderDet/cvpods/layers/csrc/cuda_version.o: No such file or directory
Could anyone give some suggestions on this issue

**Comment by FateScript** [comment]
Those files are generate by cuda compiler, please make sure your nvcc works. Thanks.
