### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by Lixia1221** [Megvii-BaseDetection/BorderDet#31]
(python) fsr@serverA2:~/BorderDet/playground/detection/coco/borderdet/borderdet.res50.fpn.coco.800size.1x$ OUTPUT_DIR /path/to/your/save_dir
OUTPUT_DIR：未找到命令

**Comment by FateScript** [comment]
the command is
```bash
pods_test/pods_train --num-gpus 8  MODEL.WEIGHTS /path/to/your/save_dir/ckpt.pth OUTPUT_DIR /path/to/your/save_dir 
```

OUTPUT_DIR is not a command, of course.

**Comment by Lixia1221** [comment]
Thanks!
