### ISSUE TITLE
train my own data

### ISSUE THREAD

**Issue by wjourney** [Megvii-BaseDetection/BorderDet#33]
hello, I want to know  that can the code train my own dataset?

**Comment by FateScript** [comment]
Write a subclass of [BaseDataset](https://github.com/Megvii-BaseDetection/BorderDet/blob/master/cvpods/data/base_dataset.py#L31), [here](https://github.com/Megvii-BaseDetection/BorderDet/blob/master/cvpods/data/datasets/coco.py#L45) is an example of how to do.
