### ISSUE TITLE
CUDA kernel function

### ISSUE THREAD

**Issue by Tarazed** [Megvii-BaseDetection/BorderDet#34]
Thanks for your great job! I want to transfer the border_align to rotated object detection and faced the error `RuntimeError: CUDA error: an illegal memory access was encountered`. After analyzing, I found it maybe due to the wrong index from the loop `CUDA_1D_KERNEL_LOOP`. In your code, I'm not clear about `dim3 grid(std::min(THCCeilDiv((long)output_size, 64L), 4096L));`. Could you please tell me why `output_size` divided by 64? Thanks.

**Comment by FateScript** [comment]
That's the dim of grid for cuda kernel to launch and its maximum value is 2048L. In [this line](https://github.com/Megvii-BaseDetection/BorderDet/blob/master/cvpods/layers/csrc/border_align/border_align_kernel.cu#L179), using 512L instead of 64L is better and we will fix it later(and remember that this value doesn't mater much).

By the way, are you willing to be an intern of our team?

**Comment by Tarazed** [comment]
> That's the dim of grid for cuda kernel to launch and its maximum value is 2048L. In [this line](https://github.com/Megvii-BaseDetection/BorderDet/blob/master/cvpods/layers/csrc/border_align/border_align_kernel.cu#L179), using 512L instead of 64L is better and we will fix it later(and remember that this value doesn't mater much).
> 
> By the way, are you willing to be an intern of our team?

Thank you for your reply! I'll try it. If it does not matter much, then I should do further debugging.

I'm willing to be the intern, can you share more details to my email? (liutianying@tongji.edu.cn)

**Comment by FateScript** [comment]
> > That's the dim of grid for cuda kernel to launch and its maximum value is 2048L. In [this line](https://github.com/Megvii-BaseDetection/BorderDet/blob/master/cvpods/layers/csrc/border_align/border_align_kernel.cu#L179), using 512L instead of 64L is better and we will fix it later(and remember that this value doesn't mater much).
> > By the way, are you willing to be an intern of our team?
> 
> Thank you for your reply! I'll try it. If it does not matter much, then I should do further debugging.
> 
> I'm willing to be the intern, can you share more details to my email? ([liutianying@tongji.edu.cn](mailto:liutianying@tongji.edu.cn))

sent.
