### ISSUE TITLE
cfg.build_shift_generator

### ISSUE THREAD

**Issue by Tangzhaotz** [Megvii-BaseDetection/BorderDet#35]
请问以下，self.shift_generator = cfg.build_shift_generator(cfg, feature_shapes)，这个build_shift_generator在代码的哪个地方，没看到。谢谢

**Comment by FateScript** [comment]
这个函数是别的模型用的，并不在borderdet的使用范畴内，属于内部代码，并没有放出

**Comment by Tangzhaotz** [comment]
好吧，谢谢
