### ISSUE TITLE
example for instance segmentation.

### ISSUE THREAD

**Issue by lxtGH** [Megvii-BaseDetection/BorderDet#39]
Again, thanks for opensourcing cvpod. I wonder how to use it for instance segmentation. I have seen there are some instance segmentation code like solo and tensormask. Could you give some example config files? @FateScript @Maycbj  Thanks!

**Comment by FateScript** [comment]
I'm sorry for not providing such a example file for you. 

We will opensource all the model in a time, and borderdet is just borderdet.

**Comment by lxtGH** [comment]
Thanks for your reply !  I just simply try some methods like mask-rcnn. It can ahiceves the same results as det2. Looking forward for all the model !
