### ISSUE TITLE
AssertionError: Requires PyTorch >= 1.3

### ISSUE THREAD

**Issue by Lixia1221** [Megvii-BaseDetection/BorderDet#40]
(python) fsr@serverA2:~/BorderDet$ python setup.py build develop
Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    assert torch_ver >= [1, 3], "Requires PyTorch >= 1.3"
AssertionError: Requires PyTorch >= 1.3

>>> print(torch.__version__)
1.7.0
 my pytorch>=1.3, why it has error?

**Comment by FateScript** [comment]
I tried on my machine with 1.7.0 and it works for me. please print your torch.__version__ to check whether another version pytorch is included during installation or not.

Thanks.
