### ISSUE TITLE
Details of enhacing the single point feature with region features?

### ISSUE THREAD

**Issue by billqxg** [Megvii-BaseDetection/BorderDet#43]
Hi, pretty nice work!

I have some questions on the combination of single point features with region features in **Table 1**.  of the paper.

For example, a B x C x H x W tensor produces another B x C x H x W x (7 * 7) with standard RoIAlign. 
A direct concatenate produces a B x (C x (7*7+1)) x H x W tensor, is it right?

And different feature extraction methods like region, border, middle leads to different numbers of points.
Can you provide more details about this part?

**Comment by Maycbj** [comment]
Thank you for your attention！
1. Region Point: B x (C x (7*7+1)) x H x W with standard RoIAlign
2. Border Point: B x (C x (4*7+1)) x H x W with standard RoIAlign 
3. Middle Border Point: B x (C x (4 + 1)) x H x W with standard RoIAlign

**Comment by billqxg** [comment]
> Thank you for your attention！
> 
> 1. Region Point: B x (C x (7*7+1)) x H x W with standard RoIAlign
> 2. Border Point: B x (C x (4*7+1)) x H x W with standard RoIAlign
> 3. Middle Border Point: B x (C x (4 + 1)) x H x W with standard RoIAlign

Thanks a lot for replying!
