### ISSUE TITLE
一个不成熟的小建议

### ISSUE THREAD

**Issue by zzl-997** [Megvii-BaseDetection/BorderDet#44]
里面的文件夹太多了，与BorderDet无关的.py文件也太多了，小白看起来太累了，搞不清楚哪里是哪里，，，
希望下次发布代码，能够条理清楚一点，那就更好了

**Comment by FateScript** [comment]
感谢您的建议，我们会在近期开始代码相关的重构工作。

**Comment by zzl-997** [comment]
感谢您的回复，您的代码能够为我们的学习提供很大帮助。



---原始邮件---
发件人: "Feng Wang"<notifications@github.com&gt;
发送时间: 2021年1月23日(周六) 中午11:04
收件人: "Megvii-BaseDetection/BorderDet"<BorderDet@noreply.github.com&gt;;
抄送: "zzl-997"<3214258853@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [Megvii-BaseDetection/BorderDet] 一个不成熟的小建议 (#44)




 
感谢您的建议，我们会在近期开始代码相关的重构工作。
