### ISSUE TITLE
I have the same question.

### ISSUE THREAD

**Issue by StetchPlane** [Megvii-BaseDetection/BorderDet#46]
https://github.com/Megvii-BaseDetection/BorderDet/issues/15#issuecomment-706919567

How can I solve this problem?
I'm looking forward to your corrections.

**Comment by Maycbj** [comment]
I'm sorry that I reply to you so late.
We have tried to use 9 anchors to train our method based on RetinaNet, which is similar to the anchor-free detectors with BorderAlign. But it is computationally intensive. So we tried different strategies to reduce the amount of calculation.
1) choose the highest score to train
2) choose the highest IoU to train
3) randomly choose an anchor to train
Strategy 3) yields the best performance in our experiments, owing to we supervise them equally to overcome overfitting.
Besides, I suggest that BorderDet based on Anchor-Free detector may be a better choice for you to get better performance.
