### ISSUE TITLE
How do you realize border feature extracting in Table 1?

### ISSUE THREAD

**Issue by rainylt** [Megvii-BaseDetection/BorderDet#48]
In the paper Table 1, you used border features in the second prediction. I'm curious about how you realize it?
It's easy to understand that ROI Align is used to extract region features as Mask rcnn, but how do you use the border features to predict the box?
Do you fill-up the border-box with zero, or reshape it to a vector and use FC layer to predict the result?

**Comment by Maycbj** [comment]
In fact, we use RoIAlign to extract border features to predict the box. As shown in the figure, the RoI size is (5, 5). It is very easy to select the index to get the border feature. Then we use the feature to predict the result by FC layers.

![image](https://user-images.githubusercontent.com/19340566/112203844-ec507b80-8c4d-11eb-9615-d2b70efb931b.png)

**Comment by rainylt** [comment]
> In fact, we use RoIAlign to extract border features to predict the box. As shown in the figure, the RoI size is (5, 5). It is very easy to select the index to get the border feature. Then we use the feature to predict the result by FC layers.
> 
> ![image](https://user-images.githubusercontent.com/19340566/112203844-ec507b80-8c4d-11eb-9615-d2b70efb931b.png)

I got it, thanks for your kind answer!
