### ISSUE TITLE
Border Feature Extraction

### ISSUE THREAD

**Issue by XavierYoungY** [Megvii-BaseDetection/BorderDet#49]
Hi there,
sorry but I couldn't find the code that is related to the border feature extraction and feature align.
I wonder where can I get them

**Comment by Maycbj** [comment]
Hi, thank you for your attention! 
The git link of the code is here. [border feature extraction](https://github.com/Megvii-BaseDetection/BorderDet/blob/master/playground/detection/coco/borderdet/borderdet.res50.fpn.coco.800size.1x/borderdet.py#L773) and [border feature align](https://github.com/Megvii-BaseDetection/cvpods/tree/master/cvpods/layers/csrc/border_align).

**Comment by XavierYoungY** [comment]
> Hi, thank you for your attention!
> The git link of the code is here. [border feature extraction](https://github.com/Megvii-BaseDetection/BorderDet/blob/master/playground/detection/coco/borderdet/borderdet.res50.fpn.coco.800size.1x/borderdet.py#L773) and [border feature align](https://github.com/Megvii-BaseDetection/cvpods/tree/master/cvpods/layers/csrc/border_align).

Thanks
