### ISSUE TITLE
TypeError: argument of type 'int' is not iterable

### ISSUE THREAD

**Issue by SnowsmileCarina** [Megvii-BaseDetection/BorderDet#5]
I use:
'pods_test --num-gpus 1 \\
MODEL.WEIGHTS BorderDet_dcnv2_X_101_64x4d_FPN_1x.pkl'
to test the trained model you provided and get the following error:

Traceback (most recent call last):
  File "/home/BorderDet/tools/test_net.py", line 207, in <module>
    args=(args,),
  File "/home/BorderDet/cvpods/engine/launch.py", line 55, in launch
    main_func(*args)
  File "/home/BorderDet/tools/test_net.py", line 189, in main
    cfg.MODEL.WEIGHTS, resume=args.resume
  File "/home/BorderDet/cvpods/checkpoint/checkpoint.py", line 169, in resume_or_load
    return self.load(path)
  File "/home/BorderDet/cvpods/checkpoint/checkpoint.py", line 105, in load
    checkpoint = self._load_file(path)
  File "/home/BorderDet/cvpods/checkpoint/detection_checkpoint.py", line 47, in _load_file
    if "model" in data and "__author__" in data:
TypeError: argument of type 'int' is not iterable

Then i go to line 47 in cvpods/checkpoint/detection_checkpoint.py and find the 'data' is not a dictionary but only a number: 119547037146038801333356

**Comment by poodarchu** [comment]
How do you get the BorderDet_dcnv2_X_101_64x4d_FPN_1x.pkl?

**Comment by SnowsmileCarina** [comment]
@poodarchu I download the model on this url you provided: https://drive.google.com/file/d/1R6a7CzwHu8iXSENZXNrWXVwaAaV-oB5_/view?usp=sharing

**Comment by SnowsmileCarina** [comment]
@poodarchu  i changed another PC and use python to only read the pkl file, the result is still the number 119547037146038801333356

**Comment by Maycbj** [comment]
@SnowsmileCarina   I think I make a mistake when I upload the _BorderDet_dcnv2_ weight, the file name needs to end with 'pth'. I have already modified the file name in google drive. 
You can rename the _BorderDet_dcnv2_X_101_64x4d_FPN_1x.pkl_  to _BorderDet_dcnv2_X_101_64x4d_FPN_1x.pth_ directly, and I think it will work.

**Comment by Duankaiwen** [comment]
@Maycbj It works! Thanks~
