### ISSUE TITLE
Can not reproduce the results.

### ISSUE THREAD

**Issue by ElectronicElephant** [Megvii-BaseDetection/BorderDet#51]
Hello,

First, thanks for your awesome work!

Recently, I tried to train the `BD_R_50_FPN_1x` model on my own. However, with 8 Titan Xp cards, I only get `38.1` mAP, far from the reported result. The config was not changed.

Strangely, when I tried to train it with 4 cards and 4 images on each card, the mAP is somewhat higher, reaching `39.8`, still below the reported mAP, though.

I have spent several days on this problem, so I resort to opening this issue. Is there anything I missed?

Here is my system info and logs. 
[log-8x2-38.1.txt](https://github.com/Megvii-BaseDetection/BorderDet/files/6387067/log-8x2-38.1.txt)
[log-4x4-39.8.txt](https://github.com/Megvii-BaseDetection/BorderDet/files/6387068/log-4x4-39.8.txt)

```
----------------------  ---------------------------------------------------------------------------------
sys.platform            linux
Python                  3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]
numpy                   1.20.1
cvpods                  0.1 @/home/usrnam/cvpods/cvpods
cvpods compiler         GCC 7.5
cvpods CUDA compiler    10.1
cvpods arch flags       sm_61
cvpods_ENV_MODULE       <not set>
PyTorch                 1.6.0 @/home/usrnam/.conda/envs/borderdet/lib/python3.7/site-packages/torch
PyTorch debug build     False
CUDA available          True
GPU 0,1,2,3,4,5,6,7     TITAN Xp
CUDA_HOME               /usr/local/cuda-10.1
NVCC                    Cuda compilation tools, release 10.1, V10.1.243
Pillow                  8.2.0
torchvision             0.7.0 @/home/usrnam/.conda/envs/borderdet/lib/python3.7/site-packages/torchvision
torchvision arch flags  sm_35, sm_50, sm_60, sm_70, sm_75
cv2                     4.5.1
----------------------  ---------------------------------------------------------------------------------
```

**Comment by Maycbj** [comment]
Thank you for your attention.
Can you reproduce the result of the FCOS? It is our baseline. The code is [here](https://github.com/Megvii-BaseDetection/BorderDet/tree/master/playground/detection/coco/fcos/fcos.res50.fpn.coco.800size.1x).

**Comment by ElectronicElephant** [comment]
Thanks. I will reopen this issue if there is anything to be updated.
