### ISSUE TITLE
HTTP Error

### ISSUE THREAD

**Issue by sh7jacobi** [Megvii-BaseDetection/BorderDet#55]
Hello. When I try to train, I have urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by sh7jacobi** [comment]
This happens with borderdet.dcnv2.x101.64x4d.fpn.coco.800size.2x

**Comment by sh7jacobi** [comment]
the same case for borderdet.dcnv2.x101.32x8d.fpn.coco.800size.2x

**Comment by sh7jacobi** [comment]
It also has the error with borderdet.x101.32x8d.fpn.coco.800size.2x, borderdet.x101.64x4d.fpn.coco.800size.2x. But It works with borderdet.res101.fpn.coco.800size.2x.

**Comment by sh7jacobi** [comment]
I guess there is no access for pretrained weight by url. I remove line weights in config.py and training has been run.

**Comment by FateScript** [comment]
Yes, the weights of that url is removed.
