### ISSUE TITLE
 no kernel image is available for execution  on the device: border_align_kernel.cu:202

### ISSUE THREAD

**Issue by HonglinChu** [Megvii-BaseDetection/BorderDet#56]
output = _C.border_align_forward(input, boxes, wh, pool_size)
RuntimeError: cuda runtime error (209) : no kernel image is available for execution on the device at /workspace/
BorderDet/cvpods/cvpods/layers/csrc/border_align/border_align_kernel.cu:202

**Comment by FateScript** [comment]
Did you compile cvpods?

**Comment by HonglinChu** [comment]
> Did you compile cvpods?

Thank you for your reply, the above error has been resolved.  I can compile cvpods successfully, and can run borderdet on RTX2060 or V100, but still can not run on RTX3090. The error message is as follows:
Exception has occurred: import error at "from cvpods import _C" :
xxx/cvpods/cvpods/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: z39tree_filter_refine_backward_edge_weightRKN2at6TensorES2_S2_S2_S2_S2_S2_S2

**Comment by FateScript** [comment]
Ok, well done.
