### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by DaiBeimin** [Megvii-BaseDetection/BorderDet#6]
After installing the requirements and building the develop, I got this error when training:
ImportError: /home/dbm/BorderDet/cvpods/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6cvpods25ComputeAdaptiveLrOnDeviceEN2at6TensorES1_dddS1_
In fact, a similar error have occurred before this, and that error was about _ZN***BorderAlign**** and I reinstalled the environment.
How can I solve this problem?

**Comment by FateScript** [comment]
This is a compile error, please provide your cuda/cudnn/pytorch version. [This issue](https://github.com/facebookresearch/detectron2/issues/686) might help you.

**Comment by DaiBeimin** [comment]
Their versions are CUDA 9.0.176, cudnn 7 and pytorch 1.3.1(pytorch is same as requirements). 
Besides, my gcc version is 5.3.1 and there was no errors when I run the command "python setup.py build develop" except some warnings of cpp. This error occurred at the line "from cvpods import _C".

The full logs is:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dbm/BorderDet/cvpods/__init__.py", line 3, in <module>
    from .utils import setup_environment
  File "/home/dbm/BorderDet/cvpods/utils/__init__.py", line 11, in <module>
    from .visualizer import colormap, random_color, VideoVisualizer, ColorMode, VisImage, Visualizer
  File "/home/dbm/BorderDet/cvpods/utils/visualizer/__init__.py", line 5, in <module>
    from .video_visualizer import *
  File "/home/dbm/BorderDet/cvpods/utils/visualizer/video_visualizer.py", line 6, in <module>
    from .visualizer import ColorMode, Visualizer, _create_text_labels, _PanopticPrediction
  File "/home/dbm/BorderDet/cvpods/utils/visualizer/visualizer.py", line 15, in <module>
    from cvpods.structures import BitMasks, Boxes, BoxMode, Keypoints, PolygonMasks, RotatedBoxes
  File "/home/dbm/BorderDet/cvpods/structures/__init__.py", line 2, in <module>
    from .boxes import Boxes, BoxMode, pairwise_iou, pairwise_ioa
  File "/home/dbm/BorderDet/cvpods/structures/boxes.py", line 8, in <module>
    from cvpods.layers import cat
  File "/home/dbm/BorderDet/cvpods/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/home/dbm/BorderDet/cvpods/layers/deform_conv.py", line 10, in <module>
    from cvpods import _C
ImportError: /home/dbm/BorderDet/cvpods/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6cvpods25ComputeAdaptiveLrOnDeviceEN2at6TensorES1_dddS1_

This error makes me so confused because the compile seems successful but in fact failed.
I have no idea about how to solve this cpp error. And thanks for your reply. Can you give me some advice?

**Comment by FateScript** [comment]
The version of NVCC you use to build cvpods or torchvision does not match the version of CUDA you are running with. This often happens when using anaconda's CUDA runtime.

Uninstalling torch and torchvision and deleting the copies from /lib/python3.6/site-packages/ and reinstalling them might fix your issue.

**Comment by DaiBeimin** [comment]
oh, thanks. I think I have figured out the problem. Pytorc 1.1.3 matchs to CUDA 10 rather than CUDA 9 and I will change the my CUDA version to see whether it is useful.
