### ISSUE TITLE
How to supplement single point feature?

### ISSUE THREAD

**Issue by oliverxudd** [Megvii-BaseDetection/BorderDet#7]
Hi there, congrats on your work!
I have a question about your experimental design.
In your paper, Section3.1, says
> Then we gradually supplement the single point feature with different
> features to refine the coarse predictions.  

So HOW did you perform such supplementation? Really curious about the motivation behind this.

**Comment by Maycbj** [comment]
1. As shown in the figure below. On the one hand, the bounding box of the human depends on the border of it(extreme point), on the other hand, do we really need to extract the whole region feature to enhance the single point feature?
2. Following the motivation, we suspect that extracting extreme point boundary point features may be important for box localization. So we compare the perfomance of the region feature, border feature and middle point of the border feature. 
![image](https://user-images.githubusercontent.com/19340566/91009278-d379dc00-e612-11ea-9bfb-7022e03732ed.png)

**Comment by oliverxudd** [comment]
thanks for the clarification!
