### ISSUE TITLE
Provide pretrained models for other algorithms?

### ISSUE THREAD

**Issue by hiyyg** [Megvii-BaseDetection/BorderDet#8]
Hi, very nice work! Could you provide the pretrained models for other algorithms, such as centernet, yolov3, fcos, etc.?

**Comment by Maycbj** [comment]
Yeah! We will provide more algorithms including detection(atss/fcos/yolo/centernet), self-supervised, classification. We have completed the reproduction of all the algorithms above, but we still need some tail-in work to do.
Please look forward to !
